### ISSUE TITLE
Use zold-java-client instead of Wts API

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-android-wallet#1]
Dependency on Wts is bad and also we can't get the API key using the key gap from the mobile.

Using the [Java API](https://github.com/amihaiemil/zold-java-client) provided by @amihaiemil will be the best solution for this app

[This](https://stackoverflow.com/questions/54376733/test-case-success-with-unit-test-but-fails-with-instrumented-test-with-nosuchmet) is a question on StackOverflow with all details of my failed attempt.

If you can help please contribute.

**Comment by amihaiemil** [comment]
@ammaratef45 As someone else said on SO, you most likely get that exception because you don't have Apache HttpClient in your classpath. zold-java-client is using Apache HttpClient so at runtime, the JVM looks for implementations of those classes. If no class is found, then boom.

This can also happen if zold-java-api is built with a different version of Apache HttpClient than what you have in your classpath. Then it may happen that a class exists, but it doesn't have a certain method (being a different version). 

Check the dependency graph of your project and make sure you have HttpClient somewhere and with a good version :)

**Comment by ammaratef45** [comment]
@amihaiemil Thank you for the reply.
I tried adding it but didn't work.
However, It can be a problem with the version.
I will try to trace this.

**Comment by amrboxit4me** [comment]
@ammaratef45 I opened the app and it asks for API Key where I get a key?

**Comment by ammaratef45** [comment]
@amrboxit4me [here](https://wts.zold.io/api)
It will ask you to create a wallet first.

**Comment by wholegroup** [comment]
@ammaratef45 I've done some research and found out that there is no possibility of using Apache HttpClient v4.x on Android. Android in self contains very old version of Apache HttpClient (probably 3.x) and disallows using third-party classes of org.apache.http.* package.
Since zold-java-client uses Apache HttpClient 4.5 it means you can't use this library in the project.

We need to improve zold-java-client at first to use this library on android.
There are some ways:
* [Apache HttpClient 5.x](https://issues.apache.org/jira/browse/HTTPCLIENT-1632) (still beta)
* Another transport library (e.g. OkHttp)
* Using an interface instead of certain implementation

**Comment by ammaratef45** [comment]
@amihaiemil Can we do this?

**Comment by amihaiemil** [comment]
@ammaratef45 as far as I can remember now, zold-java-client doesn't use any concrete class from Apache HttpClient (only builders and interfaces). Also, no fancy functionality is used, so I think it should work fine if you provide Apache HttpClient 3.x.

Can you try that? As I understand from @wholegroup 3.x should work. Or even try with 5.x.

**Comment by wholegroup** [comment]
@amihaiemil zold-java-client uses org.apache.http.impl.client.HttpClients builder. 
This class is delivered [since 4.3](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClients.html)

Android doesn't have this builder (see [here](https://android.googlesource.com/platform/external/apache-http/+/d42abb2/src/org/apache/http/impl/client))

Apache HttpComponents 5.x has been moved to ```org.apache.hc.client5.*``` package.

p.s. It's better do not use ```org.apache.http.*``` on Android at all as I understand

**Comment by g4s8** [comment]
@ammaratef45 this may help you: https://stackoverflow.com/questions/32153318/httpclient-wont-import-in-android-studio

**Comment by ammaratef45** [comment]
@g4s8 I did try that, didn't make any difference

**Comment by ammaratef45** [comment]
@wholegroup @g4s8 @amihaiemil 
The version `0.0.2` released in amihaiemil/zold-java-client#49 solved the problem.
Thank you @wholegroup for implementing the solution.
